### ISSUE TITLE
Integrate the overlapping parts of Immutable.re

### ISSUE THREAD

**Issue by glennsl** [reasonml-old/bs-containers#22]
@bordoley has asked me about the possibility of integrating the parts of Immutable.re that are overlapping with bs-containers. At the very least, this would require that bs-containers has proper cross-platform support though. See #20.

I expect @bordoley will expand on what could be moved over once he gets around to it. It seems sensible to me to shoot for a common base if we can, but I expect this will require restrictions on the design of bs-containers more than the other way around.

**Comment by bordoley** [comment]
Before jumping into details, I believe its first important to consider the goals of Immutable.re and bs-containers, as I believe this will greatly impact this decision. I'll depend on @glennsl to highlight the overarching goals of bs-containers as I don't have enough context. As for Immutable.re, the intent is to provide a rich set of immutable collections APIs that provide a consistent interface across different types, putting developers into the pit success by intentionally omitting APIs that are known to cause performance issues (eagerly evaluated map/filter for instance), and focus on concrete implementations which are "fast", also including specialized collections for performance sensitive scenarios (IntMap, IntRange, IntSet). The API surface is intended to be familiar to developers coming from the C#, Java, and Immutable.js, using naming conventions and patterns consistent with collections in those languages. A secondary goal was to design the base stream types (Streamable, Iterable, Sequence) to be compatible with a future Rx/Observable implementation. This decision is based upon my experience using Rx and the .Net collection libraries, but is clearly not a primary design goal.

When evaluating the Immutable.re API, I believe the core APIs that can be pulled into a common base are:
* [Equality](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Equality.re): Type definition for equality functions with default implementations for built-in types.
* [Ordering](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Ordering.re): Ordinal type that defines the return type of comparator functions.
* [Comparator](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Comparator.re): Type definition of the a comparator function, with implementations for built-in types.
* [Hash](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Hash.re): Type definitions for hash functions.
* [Equatable](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Equatable.re): Module type signature for types that support equality operations.
* [Comparable](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Comparable.re): Module type signature for types that support comparison and equality.
* Hashable: Module type signature for types that support hashing.
* Streamable: Module type signature for types that support basic lazy stream operations such as map, flatMap, filter, scan etc.

In addition to this base list of external interfaces, Immutable.re internally includes a base [Function module](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/utils/Functions.re) that provides common functions, and a trivial [Option module](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/utils/Option.re). Clearly all these could be sourced from a minimal base library.

Immutable.re exposes two enumeration types which implement the Streamable module signature for synchronous collections. The [Sequence module](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Sequence.re) is an implementation of monadic pull sequences that is effectively compatible with the [proposed OCaml stdlib iterator type](https://github.com/ocaml/ocaml/pull/1002). The current public type definition in Immutable.re is intentionally opaque, and does not expose the underlying variant, but the intent was to update this definition in the future to match OCaml's. A common definition of Sequence could definitely be shared in a common base library. The second enumeration type is Iterable. Iterable is defined in terms of a GADT that combines an arbitrary collection value (list, vector, set) with a single value record, providing a reducer function that supports early termination via a "while" check on each iteration of the reducer. Iterable is an order of magnitude faster than Sequence for iteration as it does not allocate memory.

The remainder of the Immutable.re API is a collection of View types (Collection, NavigableCollection, NavigableSet, KeyedCollection, Map, Indexed, etc.) which are designed to enable interop between between concrete implementations (List, Vector, HashMap, HashSet, SortedMap, SortedSet, etc.) I feel fairly strongly that all these types belong in a concrete collections library that can provide facilities (views) for interop between them. A counterpoint I've heard is that the Immutable.re API is "heavy weight", but my response to that is that it aims to be complete and support a wide range of scenarios.

One potential design split, would be to provide a base API in containers including a common Functions module, Option module, Pairs, hash/equality/comparison functions, Sequence type definition, intrinsic types (ints, int32, int64, float) and Array functions. Immutable could then depend on that module for its base, replacing it dependency on the ocaml stdlib for pervasives. Another library could be developed to provide mutable structures (Mutable.re :) including dynamic arrays, hash tables, hash sets, etc. and perhaps another library could provide a more traditional ocaml collections library (Set/Map/List module) for those who want a more minimal collections api.

**Comment by dorafmon** [comment]
Thanks @bordoley for the detailed explanation. I will wait @glennsl 's comment about the design goal of this bs-containers.

IMHO, this library should serve as the stdlib for BS/Reason. It should have rougly the same concepts offered by the OCaml stdlib, but with more useful components (as the current stdlib is a bit weak, so we have Batteries/Core). So compared to immutable.re it should be less concerned about performance, but focus on more general use cases. 

So in this regard, I would love to see these being moved to bs-containers (suddenly this seems a bad name, it should be rebase/recore/bscore to reflect the design goal):

> * [Equality](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Equality.re): Type definition for equality functions with default implementations for built-in types.
> * [Ordering](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Ordering.re): Ordinal type that defines the return type of comparator functions.
> * [Comparator](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Comparator.re): Type definition of the a comparator function, with implementations for built-in types.
> * [Hash](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Hash.re): Type definitions for hash functions.
> * [Equatable](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Equatable.re): Module type signature for types that support equality operations.
> * [Comparable](https://github.com/facebookincubator/immutable-re/blob/master/immutable/src/core/Comparable.re): Module type signature for types that support comparison and equality.
> * Hashable: Module type signature for types that support hashing.
> * Streamable: Module type signature for types that support basic lazy stream operations such as map, flatMap, filter, scan etc.

And 
> Functions module, Option module, Pairs, hash/equality/comparison functions, Sequence type definition, intrinsic types (ints, int32, int64, float) and Array functions.

And `bs-containers` should offer some basic generic containers, like `map`, `hashset`, `deque` and `stack`. 

As for naming conventions, I think currently `bs-containers` looks a lot like `immutable.re`, if there is a conflicts we can open separate issues and discuss there.

One thing I want to mention here is that should we keep this library pure OCaml (4.02 as BS currently support)? This would be a nice property to have. 

Thanks a lot.

**Comment by bordoley** [comment]
Would you guys be open to splitting this library into two parts. bs-base (or some equivalent) and bs-containers.

bs-base would be the core types discussed above. bs-containers would include ocaml List, Map, Set, Vector, Hashtbl, Heap, and maybe even the more exotic Array functions. 

Also somewhat unrelated, but I've come to quite like the approach I took with exposing a single top level module in Immutable. I'm inclinef to suggest that the base lib should use a similar top level module namespace, as not to collide with the existing ocaml stdlib. I believe core does this, where it requires you to open core at the toplevel. Even for pervasives/operators this seem preferable as it makes dependencies explicit.

**Comment by bordoley** [comment]
cc: @jordwalke

**Comment by glennsl** [comment]
I don't have any grand design goals, just some scattered thoughts really. I've already been tossing around the idea of a well-defined set of primitives to be used to implement the more abstract APIs to control consistency and interdependence better. Which aligns very well with a separate base/core-library.

So assuming our goal is to eventually take over the world and replace the OCaml std lib entirely, I think a base/core-library should consist of
* Common well-defined interfaces such as the ones proposed above, but also Mappable, Foldable etc.
* Common and well-defined implementations, the basic close-to-the-metal building blocks needed to implement every other collection, such as Array, and utility functions such as a polymorphic compare, with a focus on performance
* Common container implementations (In essence common interfaces with a shared implementation) such as Option, Result, String etc.

As a short-term goal, I think we should have this as the only direct dependency of both bs-containers and Imm.re and just proxy whatever we need from the std lib to make that happen. Then implement  it piece by piece. (Note: I don't mean to preclude either library from having its own set of internal primitives and standard interfaces if that makes more sense)

I agree that bs-containers should focus more on being basic, generic and convenient than performant.

Also agree that a single top-level module should be exposed. I don't really see any benefit to not doing so.

@bordoley What's the reason for having a Sequence type in addition to seemingly better Iterable. Just OCaml compatiblity?

@dorafmon Do you mean pure OCaml as opposed to using Reason? If so I agree we should stick with OCaml. I don't see any benefit from mixing in Reason, just costs.

**Comment by bordoley** [comment]
@glennsl: The intent of Sequence is to support zipping, eager seeking. Iterables are implemented as reduce functions, so they iterate over the full data set serially (with early termination in some cases) whenever evaluated. Sequences allow you to eagerly seek forward, hence you can create a Sequence that starts at position n and completes  n +x and which may be more efficient in some cases. More importantly because Sequences are pull based, they can be used to implement zipping.

**Comment by bordoley** [comment]
Also I have no preference about implementation language (it's just syntax), as long as the API is consistent.

**Comment by bordoley** [comment]
FWIW, I removed Mappable and Foldable (Reduceable) from Imm.re in favor of a Stream signature. One mistake most ocaml libs I've seen make is providing eagerly evaluated mapping/filtering/etc. In practice this leads to users being lazy and unintentionally over allocating significant amount memory, this is why in Imm.re all these functions are only available via Iterable, Sequence, and KeyedIterable.
