### ISSUE TITLE
Naming convention for function "variants"

### ISSUE THREAD

**Issue by glennsl** [reasonml-old/bs-containers#8]
I wish we had polls... Anyway, here's a few candidates:

* Prefix - `get`, `unsafeGet`, `maybeGet`, `lazyGet`/`maybeLazyGet`, `exnGet`/`raiseGet`
* Postfix - `get`, `getUnsafe`, `getOr`, `getLazy`/`getOrLazy`, `getExn`/`getOrRaise`

**Comment by bordoley** [comment]
FWIW, In Imm.re I settled on get (returns an option), getOrRaise (raise an exception if not found), and I'm going to add getOrDefault, which takes in a default value. 

I considered adding getOrCompute which would accept a function as fallback, but at least in my implementations it doesn't seem to consistently help in preventing the allocation of an Option, so I felt it was a bit deceiving in its value. I might reconsider that once I started digging in.

**Comment by bobzhang** [comment]
postfix seems to be better for auto-completion
